<?php

namespace Database\Seeders;

use App\Models\Chef;
use App\Models\Recipe;
use DateTime;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Recipe::truncate();
        Schema::enableForeignKeyConstraints();
        $date = new DateTime();

        $recipes = [
            [
                'title' => 'CLass Margherita Pizza',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '1.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id,
            ],
            [
                'title' => 'Vegetarian Stir-Fry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'Asian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '2.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chocolate Chip Cookies',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'American',
                'mealType' => 'dessert',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '3.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Alfredo Pasta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '4.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mango Salsa Chicken',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mexican',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '5.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Quinoa Salad with Avocado',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mediterranean',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '6.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Tomato Basil Bruschetta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '7.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Beef and Broccoli Stir-Fry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'Asian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '8.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Capers Salad',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '9.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Shrimp Scampi Pasta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '10.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Biryani',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '11.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Karachi',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '12.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Aldo Kemp',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '13.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chaplin Kebabs',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '14.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Saga with Lakki',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '15.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Japanese Ramen Soup',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'japanese',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '16.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Moroccan Chickpea Taine',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'moroccan',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '17.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Korean Bitmap',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'korean',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '18.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Greek Moussaka',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'greek',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '19.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Butter Chicken (Marg Mani)',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '20.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Thai Green Curry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'thai',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '21.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mango Lass',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'indian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '22.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Italian Tiramisu',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dessert',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '23.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Turkish Kebabs',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'turkish',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '24.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Blueberry Banana Smoothie',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'smoothie',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '25.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mexican Street Corn (Elate)',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mexican',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '26.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Russian Borscht',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'russian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '27.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'South Indian Masada Doha',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'indian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '28.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Lebanese Falafel Wrap',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'lebanese',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '29.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Brazilian Caipirinha',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'brazilian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '30.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'CLass Margherita Pizza',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '1.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Vegetarian Stir-Fry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'Asian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '2.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chocolate Chip Cookies',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'American',
                'mealType' => 'dessert',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '3.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Alfredo Pasta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '4.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mango Salsa Chicken',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mexican',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '5.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Quinoa Salad with Avocado',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mediterranean',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '6.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Tomato Basil Bruschetta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '7.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Beef and Broccoli Stir-Fry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'Asian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '8.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Capers Salad',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '9.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Shrimp Scampi Pasta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '10.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Biryani',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '11.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Karachi',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '12.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Aldo Kemp',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '13.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chaplin Kebabs',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '14.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Saga with Lakki',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '15.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Japanese Ramen Soup',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'japanese',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '16.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Moroccan Chickpea Taine',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'moroccan',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '17.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Korean Bitmap',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'korean',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '18.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Greek Moussaka',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'greek',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '19.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Butter Chicken (Marg Mani)',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '20.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Thai Green Curry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'thai',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '21.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mango Lass',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'indian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '22.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Italian Tiramisu',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dessert',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '23.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Turkish Kebabs',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'turkish',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '24.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Blueberry Banana Smoothie',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'smoothie',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '25.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mexican Street Corn (Elate)',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mexican',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '26.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Russian Borscht',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'russian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '27.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'South Indian Masada Doha',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'indian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '28.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Lebanese Falafel Wrap',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'lebanese',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '29.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Brazilian Caipirinha',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'brazilian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '30.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'CLass Margherita Pizza',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '1.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Vegetarian Stir-Fry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'Asian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '2.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chocolate Chip Cookies',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'American',
                'mealType' => 'dessert',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '3.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Alfredo Pasta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '4.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mango Salsa Chicken',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mexican',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '5.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Quinoa Salad with Avocado',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mediterranean',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '6.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Tomato Basil Bruschetta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '7.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Beef and Broccoli Stir-Fry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'Asian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '8.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Capers Salad',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '9.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Shrimp Scampi Pasta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '10.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Biryani',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '11.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Karachi',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '12.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Aldo Kemp',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '13.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chaplin Kebabs',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '14.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Saga with Lakki',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '15.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Japanese Ramen Soup',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'japanese',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '16.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Moroccan Chickpea Taine',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'moroccan',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '17.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Korean Bitmap',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'korean',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '18.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Greek Moussaka',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'greek',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '19.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Butter Chicken (Marg Mani)',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '20.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Thai Green Curry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'thai',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '21.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mango Lass',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'indian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '22.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Italian Tiramisu',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dessert',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '23.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Turkish Kebabs',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'turkish',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '24.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Blueberry Banana Smoothie',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'smoothie',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '25.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mexican Street Corn (Elate)',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mexican',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '26.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Russian Borscht',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'russian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '27.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'South Indian Masada Doha',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'indian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '28.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Lebanese Falafel Wrap',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'lebanese',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '29.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Brazilian Caipirinha',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'brazilian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '30.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'CLass Margherita Pizza',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '1.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Vegetarian Stir-Fry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'Asian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '2.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chocolate Chip Cookies',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'American',
                'mealType' => 'dessert',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '3.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Alfredo Pasta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '4.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mango Salsa Chicken',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mexican',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '5.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Quinoa Salad with Avocado',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mediterranean',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '6.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Tomato Basil Bruschetta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '7.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Beef and Broccoli Stir-Fry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'Asian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '8.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Capers Salad',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '9.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Shrimp Scampi Pasta',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '10.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Biryani',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '11.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chicken Karachi',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '12.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Aldo Kemp',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '13.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Chaplin Kebabs',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '14.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Saga with Lakki',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '15.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Japanese Ramen Soup',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'japanese',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '16.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Moroccan Chickpea Taine',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'moroccan',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '17.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Korean Bitmap',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'korean',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '18.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Greek Moussaka',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'greek',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '19.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Butter Chicken (Marg Mani)',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'pakistani',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '20.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Thai Green Curry',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'thai',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '21.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mango Lass',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'indian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '22.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Italian Tiramisu',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'italian',
                'mealType' => 'dessert',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '23.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Turkish Kebabs',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'turkish',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '24.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Blueberry Banana Smoothie',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'smoothie',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '25.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Mexican Street Corn (Elate)',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'mexican',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '26.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Russian Borscht',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'russian',
                'mealType' => 'dinner',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '27.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'South Indian Masada Doha',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'indian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '28.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Lebanese Falafel Wrap',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'lebanese',
                'mealType' => 'lunch',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '29.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ],
            [
                'title' => 'Brazilian Caipirinha',
                'price' => fake()->randomFloat(2, 49.99, 199.99),
                'rating' => rand(1, 5),
                'cooking' => 'brazilian',
                'mealType' => 'breakfast',
                'vat' => rand(10, 25),
                'item_code' => '#' . str_pad(mt_rand(1, 9999999), 7, '0', STR_PAD_LEFT),
                'offer_price' => fake()->randomFloat(2, 20.99, 49.99),
                'offer_end_at' => $date->modify('+' . rand(1, 7) . ' days')->format('Y-m-d'),
                'description' => fake()->sentence(rand(3, 9)),
                'image' => '30.webp',
                'chef_id' => Chef::inRandomOrder()->first()->id
            ]
        ];

        foreach ($recipes as $recipe) {
            Recipe::create($recipe);
        }
    }
}
